font:
  normal:
    family: Comic Mono NF
    style: Normal

  bold:
    family: Comic Mono NF
    style: Bold

  italic:
    family: Comic Mono NF
    style: Normal

  size: 9

window:
  opacity: 0.9
